### ISSUE TITLE
Logging in fails because password is not being urlencoded

### ISSUE THREAD

**Issue by roberto-mello** [Actifio/actifio-python-package#1]
If a password to the appliance has special characters, login fails because the password is not being urlencoded. parameters. The attached patch fixed that issue.

A separate issue is that the errors thrown due to inability to login give no indication that there was a login problem. Instead the errors claim the address didn't correspond to an appliance.

**Comment by roberto-mello** [comment]
Forgot to attach the patch
[login-fix.patch.gz](https://github.com/Actifio/actifio-python-package/files/3282780/login-fix.patch.gz)

**Comment by kosalaat** [comment]
Thanx for the patch. applied to the main branch and already in v1.0.1. Much appreciated.
