### ISSUE TITLE
Actifio version 9 Python issue

### ISSUE THREAD

**Issue by dmurphySE** [Actifio/actifio-python-package#6]
--
We utilize the Python Actifio modules to perform re-provisioning outside the application. Prior to version 9 it was working just fine. Now it cannot perform the re-provisioning due to CG already existing, even though we perform a dismount/delete. 

2020-10-12 11:05:34,625 - sei_actifio - ERROR - Error executing Actifio Mount server ip 10.52.61.11 exception Actifio API Error: Consistency group Silo1_QA_consistency_group already exists on appliance 2020-10-12 11:05:34,625 - sei_actifio - ERROR - udsout={}

**Comment by kosalaat** [comment]
Hi,

This is an error thrown by the API and it tells me, assuming you're using clone_database method, the sql_cg_name you specified already exists. If you're using the run_uds_command method, then in the provisioning options you have specified this in the ConsistencyGroupName.

You can check this with:

act=Actifio(.....)
out = act.run_sarg_command ('reportapps', {"a": "Silo1_QA_consistency_group"} )
print(out)

You should be able to find the CG. 

Cheers,
Ko
